// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Meocap;
#pragma warning restore 0105

namespace Meocap
{
    public static partial class MeocapSDK
    {
        public const string NativeLib = "meocap_sdk";

        static MeocapSDK()
        {
        }


        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "meocap_connect_server_char")]
        public static extern ulong meocap_connect_server_char(byte ip_a, byte ip_b, byte ip_c, byte ip_d, ushort port);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "meocap_connect_server_cstr")]
        public static extern ulong meocap_connect_server_cstr(ref sbyte endpoint);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "meocap_recv_frame")]
        public static extern int meocap_recv_frame(ulong socket, out MeoFrame frame_buf);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "meocap_clean_up")]
        public static extern int meocap_clean_up(ulong socket);

    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct Joint
    {
        public double pos0;
        public double pos1;
        public double pos2;
        public double rotation0;
        public double rotation1;
        public double rotation2;
        public double rotation3;
        public double rotation4;
        public double rotation5;
        public double rotation6;
        public double rotation7;
        public double rotation8;
    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct MeoFrame
    {
        public int frame_id;
        public double translation0;
        public double translation1;
        public double translation2;
        public Joint joints0;
        public Joint joints1;
        public Joint joints2;
        public Joint joints3;
        public Joint joints4;
        public Joint joints5;
        public Joint joints6;
        public Joint joints7;
        public Joint joints8;
        public Joint joints9;
        public Joint joints10;
        public Joint joints11;
        public Joint joints12;
        public Joint joints13;
        public Joint joints14;
        public Joint joints15;
        public Joint joints16;
        public Joint joints17;
        public Joint joints18;
        public Joint joints19;
        public Joint joints20;
        public Joint joints21;
        public Joint joints22;
        public Joint joints23;
    }



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error) : base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
