name: Create Unity Package

on: 
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        tags: true
    
    - run: |
        find Assets/Editor -name *.meta >> packageList
        find Assets/Scripts -name Meo*.meta >> packageList
        find Assets/Scripts -name meocap*.meta >> packageList
        find Assets/Plugins -name *.meta >> packageList

    - run: mkdir output
    
    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'output/output.unitypackage'
        include-files: packageList
    
    - name: Create ZIP Archive
      run: zip -r package.zip output
        
    - name: Get tag name from git describe
      id: get_tag_name
      run: |
          git fetch --tags --force
          latest_tag=$(git describe --tags)
          echo "latest_tag=$(git describe --tags)" >> "$GITHUB_ENV"
          
    - name: Read version from latest.json
      id: read_version
      run: |
        VERSION=$(jq -r '.version' ./latest.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.latest_tag }}
        release_name: MP4U ${{ env.latest_tag }} Release
        draft: false
        prerelease: false
      
    - name: Upload Github Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: package.zip
        asset_name: package.zip
        asset_content_type: application/octet-stream

    - name: Install ossutil2
      run: |
        wget https://gosspublic.alicdn.com/ossutil/1.7.6/ossutil64 -O ossutil
        chmod +x ossutil
        sudo mv ossutil /usr/local/bin


    - name: Upload files to Alibaba Cloud OSS
      env:
        ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_PLUGIN_ACCESS_KEY_ID }}
        ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_PLUGIN_ACCESS_KEY_SECRET }}
        ALIYUN_BUCKET: ${{ secrets.ALIYUN_PLUGIN_BUCKET }}
        ALIYUN_OSS_ENDPOINT: ${{ secrets.ALIYUN_PLUGIN_OSS_ENDPOINT }}
      run: |
        cp output/output.unitypackage "MeocapPluginForUnity-${{ env.VERSION }}.unitypackage"
        # Configure ossutil2
        ossutil config -i $ALIYUN_ACCESS_KEY_ID -k $ALIYUN_ACCESS_KEY_SECRET -e $ALIYUN_OSS_ENDPOINT

        # Upload files to OSS
        ossutil cp "MeocapPluginForUnity-${{ env.VERSION }}.unitypackage" oss://$ALIYUN_BUCKET/plugins/unity/ --endpoint $ALIYUN_OSS_ENDPOINT
        ossutil cp "latest.json" oss://$ALIYUN_BUCKET/plugins/unity/ --endpoint $ALIYUN_OSS_ENDPOINT


