name: Create Unity Package

on: 
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        tags: true
    
    - run: |
        find Assets/Editor -name *.meta >> packageList
        find Assets/Scripts -name Meo*.meta >> packageList
        find Assets/Scripts -name meocap*.meta >> packageList
        find Assets/Plugins -name *.meta >> packageList

    - run: mkdir output
    
    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'output/output.unitypackage'
        include-files: packageList
    
    - name: Create ZIP Archive
      run: zip -r package.zip output
        
          
    - name: Read version from latest.json
      id: read_version
      run: |
        VERSION=$(jq -r '.version' ./docs/latest.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Install ossutil2
      run: |
        wget https://gosspublic.alicdn.com/ossutil/1.7.6/ossutil64 -O ossutil
        chmod +x ossutil
        sudo mv ossutil /usr/local/bin


    - name: Upload files to Alibaba Cloud OSS
      env:
        ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_PLUGIN_ACCESS_KEY_ID }}
        ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_PLUGIN_ACCESS_KEY_SECRET }}
        ALIYUN_BUCKET: ${{ secrets.ALIYUN_PLUGIN_BUCKET }}
        ALIYUN_OSS_ENDPOINT: ${{ secrets.ALIYUN_PLUGIN_OSS_ENDPOINT }}
      run: |
        cp output/output.unitypackage "MeocapPluginForUnity-${{ env.VERSION }}.unitypackage"
        # Configure ossutil2
        ossutil config -i $ALIYUN_ACCESS_KEY_ID -k $ALIYUN_ACCESS_KEY_SECRET -e $ALIYUN_OSS_ENDPOINT

        # Upload files to OSS
        ossutil cp -f -u "MeocapPluginForUnity-${{ env.VERSION }}.unitypackage" oss://$ALIYUN_BUCKET/plugins/unity/ --endpoint $ALIYUN_OSS_ENDPOINT
        ossutil cp -f -u -r ./docs/ oss://$ALIYUN_BUCKET/plugins/unity/docs --endpoint $ALIYUN_OSS_ENDPOINT


